<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in application.config.old
 */
return array(
    'modules' => array(
        'Application',
        'ZF\\Apigility',
        'ZF\\Apigility\\Provider',
        'AssetManager',
        'ZF\\ApiProblem',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZF\\DevelopmentMode',
        'ZF\Apigility\Documentation',
        'ZF\\Apigility\\Documentation\\Swagger',
        'DoctrineModule',
        'DoctrineORMModule',
        'ZendDbMigrations',
        'Server',
        'ZfcBase',
        'ZfcUser',
        'BjyAuthorize',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        ),
        'config_cache_enabled'     => true,
        // The key used to create the configuration cache file name.
        //'config_cache_key'         => "2245023265ae4cf87d02c8b6ba991139",
        // Whether or not to enable a module class map cache.
        // If enabled, creates a module class map cache which will be used
        // by in future requests, to reduce the autoloading process.
        'module_map_cache_enabled' => true,
        // The key used to create the class map cache file name.
        'module_map_cache_key'     => "496fe9daf9baed5ab03314f04518b928",
        // The path in which to cache merged configuration.
        'cache_dir'                => "data/cache",
    )
);
